export function dashboardHtml(hostId: string): string {
  const safeHost = hostId.replace(/[^a-z0-9-]/g, '');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer">
<title>BotDesk Owner</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0c0c0c;color:#fff}*{box-sizing:border-box}body{margin:0;padding:24px;background:radial-gradient(circle at 80% 0,#3c0c09,#0c0c0c 42%)}main{max-width:620px;margin:auto}.eyebrow{color:#ff665c;font-weight:900;letter-spacing:.14em;font-size:12px}h1{font-size:52px;margin:8px 0}h2{font-size:20px;margin-top:0}.card{border:1px solid #403a34;background:#171513;padding:22px;margin:18px 0}.mode{font-size:36px;font-weight:900;letter-spacing:.05em;color:#ff665c}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}button{min-height:56px;border:1px solid #635b52;background:#24211e;color:white;font-weight:900;font-size:15px;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}button:focus-visible,input:focus-visible{outline:3px solid #ff665c;outline-offset:3px}button.arm{background:#d3291f}button.stop{background:#f14235;color:white}.meta{color:#b9afa5;line-height:1.5}.alert{color:#ff665c;line-height:1.5;min-height:24px}.clock{font-size:22px;color:#ff665c;font-variant-numeric:tabular-nums}label{display:block;color:#b9afa5;font-size:13px}input{display:block;width:100%;min-width:0;margin:8px 0 16px;border:1px solid #635b52;background:#24211e;color:white;padding:12px;font-size:16px}#save-schedule{width:100%;margin-top:6px}img{display:none;width:100%;border:2px solid #d3291f;margin-top:15px}@media(max-width:520px){h1{font-size:40px}.row{grid-template-columns:1fr}}
</style></head><body><main><p class="eyebrow">REMOTE OWNER CONTROL</p><h1>BOTDESK</h1><div class="card"><div id="mode" class="mode" aria-live="polite">CONNECTING</div><p id="detail" class="meta">Checking ${safeHost}…</p><p id="countdown" class="clock"></p><p id="alert" class="alert" role="alert"></p></div><div class="row"><button class="arm" data-action="armed" disabled>GO LIVE — 8 HOURS</button><button data-action="paused" disabled>PAUSE</button><button class="stop" data-action="off" disabled>STOP NOW</button><button id="preview" disabled>SHOW SCREEN</button></div><div class="card"><h2>Set a time window</h2><p class="meta" id="timezone"></p><div class="row"><label>START<input id="schedule-start" type="datetime-local" required></label><label>END<input id="schedule-end" type="datetime-local" required></label></div><button id="save-schedule" disabled>SAVE SCHEDULE</button><p class="meta" id="schedule-detail">Choose one window up to 12 hours. BotDesk starts and stops automatically. STOP and PAUSE cancel it.</p></div><div class="card"><p class="meta">Prepare BotDesk once on the PC, then use these controls while you’re away. The PC must be awake and online. The local Ctrl + Shift + F12 emergency stop remains active.</p><img id="screen" alt="BotDesk screen preview at the time requested"><p id="preview-time" class="meta"></p></div><script>
const host=${JSON.stringify(safeHost)};const token=location.hash.slice(1);const hasToken=/^[A-Za-z0-9_-]{43,128}$/.test(token);const screen=document.querySelector('#screen');let controlBusy=false;let previewBusy=false;let scheduleBusy=false;let current=null;let syncedSchedule=false;
function alertMessage(message){document.querySelector('#alert').textContent=message}
function clearScreen(){screen.removeAttribute('src');screen.style.display='none';document.querySelector('#preview-time').textContent=''}
function localDateValue(d){const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
const nextStart=new Date();nextStart.setHours(6,0,0,0);if(nextStart<=new Date())nextStart.setDate(nextStart.getDate()+1);const nextEnd=new Date(nextStart);nextEnd.setHours(18,0,0,0);document.querySelector('#schedule-start').value=localDateValue(nextStart);document.querySelector('#schedule-end').value=localDateValue(nextEnd);document.querySelector('#timezone').textContent='Times on this phone: '+Intl.DateTimeFormat().resolvedOptions().timeZone;
async function request(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+token,'content-type':'application/json','x-request-id':crypto.randomUUID()},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(body?25000:10000),cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
function countdown(){const el=document.querySelector('#countdown');if(!current){el.textContent='';return}const end=current.liveEndsAt||current.expiresAt;const waiting=current.schedule&&Date.now()<current.schedule.startsAt;const target=end||(waiting?current.schedule.startsAt:null);if(!target){el.textContent=current.schedulePending?'Waiting for the PC to connect':'';return}const seconds=Math.max(0,Math.ceil((target-Date.now())/1000));const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;el.textContent=(waiting&&!end?'Starts in ':'Live for ')+h+'h '+String(m).padStart(2,'0')+'m '+String(s).padStart(2,'0')+'s'}
function render(s){current=s;const live=['armed','running'].includes(s.mode);document.querySelector('#mode').textContent=live?'LIVE':(s.schedulePending?'SCHEDULED':(s.mode||'off').toUpperCase());document.querySelector('#detail').textContent=(s.hostOnline?'PC ONLINE':'PC OFFLINE')+(s.activeBot?' · '+s.activeBot:'');document.querySelector('[data-action="armed"]').disabled=!hasToken||controlBusy;document.querySelector('#preview').disabled=!hasToken||!s.hostOnline||!live||previewBusy;document.querySelector('#save-schedule').disabled=!hasToken||scheduleBusy;if(!s.hostOnline||!live)clearScreen();if(s.schedule){document.querySelector('#schedule-detail').textContent='Saved: '+new Date(s.schedule.startsAt).toLocaleString()+' → '+new Date(s.schedule.endsAt).toLocaleString()+'. Access resumes inside this window if the PC reconnects.';if(!syncedSchedule){document.querySelector('#schedule-start').value=localDateValue(new Date(s.schedule.startsAt));document.querySelector('#schedule-end').value=localDateValue(new Date(s.schedule.endsAt));syncedSchedule=true}}else{document.querySelector('#schedule-detail').textContent='Choose one window up to 12 hours. BotDesk starts and stops automatically. STOP and PAUSE cancel it.'}if(s.scheduleError)alertMessage(s.scheduleError);countdown()}
async function refresh(){if(!hasToken)return;try{render(await request('/api/owner/'+host+'/status'))}catch(e){current=null;countdown();document.querySelector('#mode').textContent='UNKNOWN';document.querySelector('#detail').textContent='Could not verify the PC state';document.querySelector('[data-action="armed"]').disabled=true;document.querySelector('#preview').disabled=true;clearScreen();alertMessage(e.message)}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const mode=b.dataset.action;if(mode==='armed'&&controlBusy)return;controlBusy=true;alertMessage(mode==='armed'?'Starting access…':'Stopping control and cancelling the schedule…');try{const s=await request('/api/owner/'+host+'/state',{mode,minutes:480});render(s);alertMessage(s.confirmed?(s.mode==='armed'?'PC is live.': 'PC confirmed '+s.mode.toUpperCase()): (s.schedule?'Timer saved. Access starts when the PC reconnects.':'Relay is OFF and the schedule is cancelled. PC could not confirm.'))}catch(e){alertMessage(e.message)}finally{controlBusy=false;await refresh()}});
document.querySelector('#save-schedule').onclick=async()=>{if(scheduleBusy)return;const startsAt=new Date(document.querySelector('#schedule-start').value).getTime(),endsAt=new Date(document.querySelector('#schedule-end').value).getTime();if(!Number.isFinite(startsAt)||!Number.isFinite(endsAt)||endsAt<=startsAt||endsAt<=Date.now()||endsAt-startsAt>12*3600000){alertMessage('Choose an end after the start, within 12 hours.');return}scheduleBusy=true;document.querySelector('#save-schedule').disabled=true;try{render(await request('/api/owner/'+host+'/schedule',{startsAt,endsAt}));alertMessage('Schedule saved. BotDesk will start and stop automatically.')}catch(e){alertMessage(e.message)}finally{scheduleBusy=false;await refresh()}};
document.querySelector('#preview').onclick=async()=>{if(previewBusy)return;previewBusy=true;clearScreen();try{const r=await request('/api/owner/'+host+'/command',{name:'screenshot',args:{}});const capture=r.result?.image||r.result;if(!capture||!['image/png','image/jpeg'].includes(capture.mimeType)||typeof capture.data!=='string'||capture.data.length>8388608)throw new Error('Invalid preview');screen.src='data:'+capture.mimeType+';base64,'+capture.data;screen.style.display='block';document.querySelector('#preview-time').textContent='Captured '+new Date().toLocaleTimeString();alertMessage('')}catch(e){alertMessage(e.message)}finally{previewBusy=false;await refresh()}};
async function poll(){await refresh();setTimeout(poll,5000)}
if(hasToken){document.querySelectorAll('[data-action]').forEach(b=>b.disabled=false);document.querySelector('#save-schedule').disabled=false;poll()}else{document.querySelector('#mode').textContent='LOCKED';document.querySelector('#detail').textContent='Open the private owner link saved during setup.'}setInterval(countdown,1000);
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearScreen();else refresh()});
</script></main></body></html>`;
}



